//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaDBleWebApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horse
    {
        public int Id { get; set; }
        public Nullable<int> StableId { get; set; }
        public string Identifier { get; set; }
        public Nullable<int> Links { get; set; }
    
        public virtual Stable Stable { get; set; }
    }
}
