//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaDBleWebApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stable()
        {
            this.Horses = new HashSet<Horse>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Address { get; set; }
        public string Identifier { get; set; }
        public Nullable<int> Links { get; set; }
        public Nullable<int> Stalls { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horse> Horses { get; set; }
    }
}
